[2025-10-18T22:00:43.643+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-18T22:00:46.852+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_quality_etl.fetch_task scheduled__2025-10-18T21:00:00+00:00 [queued]>
[2025-10-18T22:00:48.203+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_quality_etl.fetch_task scheduled__2025-10-18T21:00:00+00:00 [queued]>
[2025-10-18T22:00:48.204+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-18T22:00:49.903+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_task> on 2025-10-18 21:00:00+00:00
[2025-10-18T22:00:49.944+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'air_quality_etl', 'fetch_task', 'scheduled__2025-10-18T21:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/stock_etl_dag.py', '--cfg-path', '/tmp/tmp_7hkdhtf']
[2025-10-18T22:00:49.954+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask fetch_task
[2025-10-18T22:00:49.963+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=183) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-18T22:00:49.964+0000] {standard_task_runner.py:64} INFO - Started process 191 to run task
[2025-10-18T22:00:57.934+0000] {task_command.py:426} INFO - Running <TaskInstance: air_quality_etl.fetch_task scheduled__2025-10-18T21:00:00+00:00 [running]> on host 8ab34fa70f13
[2025-10-18T22:01:11.462+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='air_quality_etl' AIRFLOW_CTX_TASK_ID='fetch_task' AIRFLOW_CTX_EXECUTION_DATE='2025-10-18T21:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-18T21:00:00+00:00'
[2025-10-18T22:01:11.466+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-18T22:01:11.547+0000] {stock_etl_dag.py:33} INFO - Fetching air quality data for Nairobi
[2025-10-18T22:01:12.266+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-18T22:01:12.270+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_etl_dag.py", line 35, in fetch_data
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://air-quality-api.open-meteo.com/v1/air-quality?latitude=-1.286389&longitude=36.817223&hourly=pm10,pm2_5,o3,co,no2,so2,uv_index&timezone=Africa%2FNairobi
[2025-10-18T22:01:17.980+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=air_quality_etl, task_id=fetch_task, run_id=scheduled__2025-10-18T21:00:00+00:00, execution_date=20251018T210000, start_date=20251018T220046, end_date=20251018T220117
[2025-10-18T22:01:20.020+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task fetch_task (400 Client Error: Bad Request for url: https://air-quality-api.open-meteo.com/v1/air-quality?latitude=-1.286389&longitude=36.817223&hourly=pm10,pm2_5,o3,co,no2,so2,uv_index&timezone=Africa%2FNairobi; 191)
[2025-10-18T22:01:24.239+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-18T22:01:27.153+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-18T22:01:27.426+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
