[2025-10-17T15:28:50.637+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-17T15:28:50.884+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_quality_etl.fetch_task scheduled__2025-10-17T14:00:00+00:00 [queued]>
[2025-10-17T15:28:50.904+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_quality_etl.fetch_task scheduled__2025-10-17T14:00:00+00:00 [queued]>
[2025-10-17T15:28:50.905+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-10-17T15:28:51.066+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_task> on 2025-10-17 14:00:00+00:00
[2025-10-17T15:28:51.086+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'air_quality_etl', 'fetch_task', 'scheduled__2025-10-17T14:00:00+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/stock_etl_dag.py', '--cfg-path', '/tmp/tmpwhcf2jyx']
[2025-10-17T15:28:51.091+0000] {standard_task_runner.py:91} INFO - Job 96: Subtask fetch_task
[2025-10-17T15:28:51.224+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=643) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-17T15:28:51.225+0000] {standard_task_runner.py:64} INFO - Started process 645 to run task
[2025-10-17T15:28:51.476+0000] {task_command.py:426} INFO - Running <TaskInstance: air_quality_etl.fetch_task scheduled__2025-10-17T14:00:00+00:00 [running]> on host 7ed111c059a0
[2025-10-17T15:28:54.422+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='air_quality_etl' AIRFLOW_CTX_TASK_ID='fetch_task' AIRFLOW_CTX_EXECUTION_DATE='2025-10-17T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-17T14:00:00+00:00'
[2025-10-17T15:28:54.424+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-17T15:28:54.472+0000] {stock_etl_dag.py:33} INFO - Fetching air quality data for Nairobi
[2025-10-17T15:28:55.421+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-17T15:28:55.422+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_etl_dag.py", line 35, in fetch_data
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://air-quality-api.open-meteo.com/v1/air-quality?latitude=-1.286389&longitude=36.817223&hourly=pm10,pm2_5,o3,co,no2,so2,uv_index&timezone=Africa%2FNairobi
[2025-10-17T15:28:55.742+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=air_quality_etl, task_id=fetch_task, run_id=scheduled__2025-10-17T14:00:00+00:00, execution_date=20251017T140000, start_date=20251017T152850, end_date=20251017T152855
[2025-10-17T15:28:55.882+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 96 for task fetch_task (400 Client Error: Bad Request for url: https://air-quality-api.open-meteo.com/v1/air-quality?latitude=-1.286389&longitude=36.817223&hourly=pm10,pm2_5,o3,co,no2,so2,uv_index&timezone=Africa%2FNairobi; 645)
[2025-10-17T15:28:55.917+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-17T15:28:56.033+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-17T15:28:56.053+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
