[2025-10-20T12:17:38.513+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-20T12:17:42.313+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_quality_etl.fetch_task scheduled__2025-10-20T11:00:00+00:00 [queued]>
[2025-10-20T12:17:43.239+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_quality_etl.fetch_task scheduled__2025-10-20T11:00:00+00:00 [queued]>
[2025-10-20T12:17:43.239+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-10-20T12:17:45.391+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_task> on 2025-10-20 11:00:00+00:00
[2025-10-20T12:17:45.442+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'air_quality_etl', 'fetch_task', 'scheduled__2025-10-20T11:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/stock_etl_dag.py', '--cfg-path', '/tmp/tmpqye4xlbr']
[2025-10-20T12:17:45.454+0000] {standard_task_runner.py:91} INFO - Job 23: Subtask fetch_task
[2025-10-20T12:17:45.478+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=214) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-20T12:17:45.480+0000] {standard_task_runner.py:64} INFO - Started process 218 to run task
[2025-10-20T12:17:52.614+0000] {task_command.py:426} INFO - Running <TaskInstance: air_quality_etl.fetch_task scheduled__2025-10-20T11:00:00+00:00 [running]> on host 7291be9e0ed3
[2025-10-20T12:18:16.358+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='air_quality_etl' AIRFLOW_CTX_TASK_ID='fetch_task' AIRFLOW_CTX_EXECUTION_DATE='2025-10-20T11:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-20T11:00:00+00:00'
[2025-10-20T12:18:16.364+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-20T12:18:16.447+0000] {stock_etl_dag.py:33} INFO - Fetching air quality data for Nairobi
[2025-10-20T12:18:17.199+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-20T12:18:17.202+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_etl_dag.py", line 35, in fetch_data
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://air-quality-api.open-meteo.com/v1/air-quality?latitude=-1.286389&longitude=36.817223&hourly=pm10,pm2_5,o3,co,no2,so2,uv_index&timezone=Africa%2FNairobi
[2025-10-20T12:18:20.294+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=air_quality_etl, task_id=fetch_task, run_id=scheduled__2025-10-20T11:00:00+00:00, execution_date=20251020T110000, start_date=20251020T121742, end_date=20251020T121820
[2025-10-20T12:18:22.135+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 23 for task fetch_task (400 Client Error: Bad Request for url: https://air-quality-api.open-meteo.com/v1/air-quality?latitude=-1.286389&longitude=36.817223&hourly=pm10,pm2_5,o3,co,no2,so2,uv_index&timezone=Africa%2FNairobi; 218)
[2025-10-20T12:18:22.210+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-20T12:18:25.693+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-20T12:18:26.148+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
