[2025-10-14T00:22:57.741+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-14T00:22:57.785+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_market_etl.extract_task manual__2025-10-14T00:19:18.860927+00:00 [queued]>
[2025-10-14T00:22:57.796+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_market_etl.extract_task manual__2025-10-14T00:19:18.860927+00:00 [queued]>
[2025-10-14T00:22:57.796+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 5
[2025-10-14T00:22:57.856+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_task> on 2025-10-14 00:19:18.860927+00:00
[2025-10-14T00:22:57.874+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_market_etl', 'extract_task', 'manual__2025-10-14T00:19:18.860927+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/stock_etl_dag.py', '--cfg-path', '/tmp/tmp18j8oasp']
[2025-10-14T00:22:57.881+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask extract_task
[2025-10-14T00:22:57.884+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=297) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-14T00:22:57.885+0000] {standard_task_runner.py:64} INFO - Started process 299 to run task
[2025-10-14T00:22:58.102+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_market_etl.extract_task manual__2025-10-14T00:19:18.860927+00:00 [running]> on host 9d4269c8615b
[2025-10-14T00:22:58.335+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_market_etl' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2025-10-14T00:19:18.860927+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-14T00:19:18.860927+00:00'
[2025-10-14T00:22:58.340+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-14T00:22:58.356+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-14T00:22:58.357+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_etl_dag.py", line 20, in extract_stock_data
    raise ValueError("API_KEY environment variable is not set")
ValueError: API_KEY environment variable is not set
[2025-10-14T00:22:58.371+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_market_etl, task_id=extract_task, run_id=manual__2025-10-14T00:19:18.860927+00:00, execution_date=20251014T001918, start_date=20251014T002257, end_date=20251014T002258
[2025-10-14T00:22:58.490+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task extract_task (API_KEY environment variable is not set; 299)
[2025-10-14T00:22:58.503+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-14T00:22:58.528+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T00:22:58.655+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
